name: Run Python Script Periodically

on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  run-python-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python3-version: '3.11'

      - name: Install requirements
        run: pip install -r requirements.txt

      - name: Execute script
        run: python ./ptrack.py

